
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle: 
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - 'index.md'
  - 'Binary Tree':
    - '250 - count univalue subtrees': 'binary-tree/250.md'
    - 'binary-tree/page.md'
  - 'Binary Search Tree':
    - 'binary-search-tree/page-1.md'
    - 'binary-search-tree/page-2.md'
  - 'Linked List':
    - "something": none

site_name: Never Stop Coding
repo_name: solve-and-evolve
repo_url: https://github.com/faerlin-developer/solve-and-evolve